require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'


target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

target 'desenvolvekids' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
 

  target 'desenvolvekidsTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

end

target 'desenvolvekids-tvOS' do
  # Pods for desenvolvekids-tvOS

  target 'desenvolvekids-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
